version: '3.9'

services:
  flask-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development  # Change to production for production mode
      FLASK_APP: backend.main.py
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: development
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
