version: '3.9'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development  # Change to production for production mode
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: flaskdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
