version: "3.8"

services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db:
        condition: service_healthy
    command: ["python", "main.py"]

  db:
    image: postgres:13
    container_name: db
    env_file:
      - .db.env
    environment:
      POSTGRES_USER: sungrohRyu
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ciae
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - ./pData:/var/lib/postgresql/data

main:
  contaier_name: ciae-main
  build:
    context: .
    dockerfile: Dockerfile
  ports:
    - 포트 잘 모르겠다
  depends_on:
    db:
      condition: service_healthy
    links:
      - db